from tkinter import Tk,Label,Button,Entry,messagebox,PhotoImage,Toplevel
import sqlite3 
Co=sqlite3.connect("D.db")
def Nerissa():
    C=En.get()
    En.delete(0,"end")
    En1.delete(0,"end")
    En2.delete(0,"end")
    En3.delete(0,"end")
    En4.delete(0,"end")
    En5.delete(0,"end")
    Cu=Co.execute("select * from Productos where Codigo=? ",(C, ))
    U1=Cu.fetchone()
    if U1!=None:
        En1.insert(0,U1[1])
        En2.insert(0,U1[2])
        En3.insert(0,U1[3])
        En4.insert(0,U1[4])
        P=U1[4]*120/100
        En5.insert(0,P)
        S=En3.get()
        U=int(S)
        if U>80:
            En3.config(bg="green")
        if U>20 and U<80:
            En3.config(bg="yellow")
        if U<20:
            En3.config(bg="red")
    else:    
        messagebox.showerror("Error","El articulo no existe")
def Mumei():
    Elizabeth.destroy()
def Shiori():
    U2=En6.get()
    C1=En7.get()
    En6.delete(0,"end")
    En7.delete(0,"end")
    Cu1=Co.execute("select * from Usuarios where Usuario=? and Contrasenia=?",(U2,C1))
    J=Cu1.fetchone()
    if J!=None:
        Fuwamoco.destroy()
        if J[3]==1:
            Elizabeth.deiconify()
        if J[3]==2:
            Elizabeth.deiconify()
            B3=Button(Elizabeth)
            def Nerissa7(event):
                B3.config(bg="blue",fg="white")
                B3.bind("<Enter>",Nerissa7)
            def Nerissa8(event):
                B3.config(bg="white",fg="blue")
                B3.bind("<Leave>",Nerissa8)    
            B3.config(text="Agregar",bg="white",fg="blue",font=("arial",10,"normal"),command=Cecilia)
            B3.place(x=300,y=50)
        if J[3]==3:
            Elizabeth.deiconify()
            B3=Button(Elizabeth)
            def Nerissa9(event):
                B3.config(bg="blue",fg="white")
                B3.bind("<Enter>",Nerissa9)
            def Nerissa10(event):
                B3.config(bg="white",fg="blue")
                B3.bind("<Leave>",Nerissa10)
            B3.config(text="Agregar",bg="white",fg="blue",font=("arial",10,"normal"),command=Cecilia)
            B3.place(x=300,y=50)
            B4=Button(Elizabeth)
            def Nerissa11(event):
                B4.config(bg="blue",fg="white")
                B4.bind("<Enter>",Nerissa11)
            def Nerissa12(event):
                B4.config(bg="white",fg="blue")
                B4.bind("<Leave>",Nerissa12)
            B4.config(text="Eliminar",bg="white",fg="blue",font=("arial",10,"normal"),command=Raora)
            B4.place(x=300,y=100)
    else:
        messagebox.showerror("Error","El usuario no existe")
def Cecilia():
    A=En1.get()
    F=En2.get()
    G=En3.get()
    H=En4.get()
    Co.execute("insert into Productos(Codigo,Descripcion,Stock,Precio costo)values(?,?,?,?)",(A,F,G,H))
    Co.commit()
def Raora():
    D=En.get()
    Co.execute("delete from Productos where Codigo=?",(D, ))
    Co.commit()
Elizabeth=Tk()
Elizabeth.title("Ferreteria 1.0")
Elizabeth.config(width=500,height=500,bg="red")
E=Label(Elizabeth)
E.config(text="Codigo: ",bg="white",fg="blue",font=("arial",10,"normal"))
E.place(x=70,y=10)
E1=Label(Elizabeth)
E1.config(text="Codigo: ",bg="white",fg="blue",font=("arial",10,"normal"))
E1.place(x=70,y=50)
E2=Label(Elizabeth)
E2.config(text="Descripcion: ",bg="white",fg="blue",font=("arial",10,"normal"))
E2.place(x=70,y=100)
E3=Label(Elizabeth)
E3.config(text="Stock: ",bg="white",fg="blue",font=("arial",10,"normal"))
E3.place(x=70,y=150)
E4=Label(Elizabeth)
E4.config(text="Precio costo: ",bg="white",fg="blue",font=("arial",10,"normal"))
E4.place(x=70,y=200)
E5=Label(Elizabeth)
E5.config(text="Precio venta: ",bg="white",fg="blue",font=("arial",10,"normal"))
E5.place(x=70,y=250)
En=Entry(Elizabeth)
En.config(fg="red")
def Nerissa2(event):
    Nerissa()
En.bind("<Return>",Nerissa2)
En.place(x=140,y=13)
En1=Entry(Elizabeth)
En1.config(fg="blue")
En1.place(x=140,y=53)
En2=Entry(Elizabeth)
En2.config(fg="blue")
En2.place(x=160,y=103)
En3=Entry(Elizabeth)
En3.config(fg="blue")
En3.place(x=130,y=153)
En4=Entry(Elizabeth)
En4.config(fg="blue")
En4.place(x=160,y=203)
En5=Entry(Elizabeth)
En5.config(fg="blue")
En5.place(x=160,y=253)
B=Button(Elizabeth)
def Nerissa3(event):
    B.config(bg="blue",fg="white")
B.bind("<Enter>",Nerissa3)
def Nerissa4(event):
    B.config(bg="white",fg="blue")
B.bind("<Leave>",Nerissa4)
B.config(text="Buscar",bg="white",fg="blue",font=("arial",10,"normal"),command=Nerissa)
B.place(x=300,y=10)
B2=Button(Elizabeth)
def Nerissa5(event):
    B2.config(bg="blue",fg="white")
B2.bind("<Enter>",Nerissa5)
def Nerissa6(event):
    B2.config(bg="white",fg="blue")
B2.bind("<Leave>",Nerissa6)
B2.config(text="Salir",bg="white",fg="blue",font=("arial",10,"normal"),command=Mumei)
B2.place(x=450,y=450)
Im=PhotoImage(file="imagen5.png")
Im=Im.subsample(6)
E6=Label(Elizabeth)
E6.config(image=Im)
E6.place(x=100,y=280)
Elizabeth.withdraw()
Fuwamoco=Toplevel(Elizabeth)
Fuwamoco.title("Login")
Fuwamoco.config(width=500,height=400,bg="black")
E6=Label(Fuwamoco)
E6.config(text="Usuario: ",fg="light blue",font=("arial",20,"normal"))
E6.place(x=70,y=50)
E7=Label(Fuwamoco)
E7.config(text="Contraseña: ",fg="pink",font=("arial",20,"normal"))
E7.place(x=70,y=150)
En6=Entry(Fuwamoco)
En6.config(fg="light blue")
En6.place(x=200,y=60)
En7=Entry(Fuwamoco)
En7.config(fg="pink")
En7.place(x=250,y=160)
B=Button(Fuwamoco)
B.config(text="Iniciar sesion",bg="light blue",fg="pink",font=("arial",20,"normal"),command=Shiori)
B.place(x=150,y=250)
Elizabeth.mainloop()